import type { TapMessagingService } from "trusted-agents-core";
import type { RouteHandler } from "../router.js";
import { asRecord, isNonEmptyString, isOptionalString, requireBody } from "../validation.js";

interface SendMessageBody {
	peer: string;
	text: string;
	scope?: string;
	/**
	 * Reply-loop guard — TAP agents set this to `true` on auto-generated
	 * replies so the peer's runtime can recognize them and avoid replying
	 * again. Without this flag on the wire, two agents that auto-reply to
	 * each other can loop forever. See `packages/core/src/runtime/service.ts`
	 * `sendMessage` → `buildOutgoingMessageRequest` which threads this
	 * through into the message request metadata.
	 */
	autoGenerated?: boolean;
	/** Pay the peer's priority attention price so the message can wake it. */
	priority?: boolean;
}

function isSendMessageBody(value: unknown): value is SendMessageBody {
	const v = asRecord(value);
	if (!v) return false;
	if (!isNonEmptyString(v.peer)) return false;
	if (typeof v.text !== "string") return false;
	if (!isOptionalString(v.scope)) return false;
	if (v.autoGenerated !== undefined && typeof v.autoGenerated !== "boolean") return false;
	if (v.priority !== undefined && typeof v.priority !== "boolean") return false;
	return true;
}

/**
 * POST /api/messages — send a TAP message to a connected peer through the
 * daemon's owned transport. Body shape:
 * `{ peer, text, scope?, autoGenerated?, priority? }`.
 */
export function createMessagesRoute(service: TapMessagingService): RouteHandler {
	return async (_params, body) => {
		requireBody(
			body,
			isSendMessageBody,
			"messages POST requires { peer: string, text: string, scope?: string, autoGenerated?: boolean, priority?: boolean }",
		);
		const options =
			body.autoGenerated !== undefined || body.priority !== undefined
				? {
						...(body.autoGenerated !== undefined ? { autoGenerated: body.autoGenerated } : {}),
						...(body.priority !== undefined ? { priority: body.priority } : {}),
					}
				: undefined;
		return await service.sendMessage(body.peer, body.text, body.scope, options);
	};
}
