import { readFile } from "node:fs/promises";
import { request } from "node:http";
import { dirname, join } from "node:path";
import type { TapNotification, TapNotificationType } from "trusted-agents-tapd";

export type { TapNotification, TapNotificationType };

const DEFAULT_SOCKET_NAME = ".tapd.sock";
const TOKEN_FILE_NAME = ".tapd-token";
const DEFAULT_DATA_DIR = ".trustedagents";
const DEFAULT_TIMEOUT_MS = 10_000;

/**
 * Thrown when the tapd Unix socket is missing/unreachable. The OpenClaw plugin
 * uses this to surface a clear "tapd is not running" error to the operator
 * without crashing Gateway.
 */
export class TapdNotRunningError extends Error {
	constructor(public readonly socketPath: string) {
		super(
			`tapd is not running (socket not found at ${socketPath}). Start it with: tap daemon start`,
		);
		this.name = "TapdNotRunningError";
	}
}

/**
 * Thrown for any non-2xx HTTP response from tapd. Carries the structured
 * error code/message that tapd's response envelope produces so callers can
 * surface them verbatim.
 */
export class TapdHttpError extends Error {
	constructor(
		public readonly status: number,
		public readonly code: string,
		message: string,
	) {
		super(message);
		this.name = "TapdHttpError";
	}
}

export interface OpenClawTapdClientOptions {
	dataDir?: string;
	socketPath?: string;
	timeoutMs?: number;
}

/**
 * Resolve the tapd Unix socket path using the same precedence order the
 * rest of TAP uses for data dir / socket discovery (F5.1):
 *
 *   explicit `socketPath`
 *     > explicit `dataDir`
 *     > `process.env.TAP_DATA_DIR`
 *     > `~/.trustedagents`
 *
 * Honoring `TAP_DATA_DIR` is critical for isolated OpenClaw deployments
 * that start tapd under a non-default data dir — without it, the plugin
 * silently talks to the operator's default daemon, which is a cross-agent
 * isolation bug.
 */
export function resolveSocketPath(options: OpenClawTapdClientOptions): string {
	if (options.socketPath) return options.socketPath;
	if (options.dataDir) return join(options.dataDir, DEFAULT_SOCKET_NAME);
	const envDataDir = process.env.TAP_DATA_DIR;
	if (envDataDir && envDataDir.length > 0) return join(envDataDir, DEFAULT_SOCKET_NAME);
	const fallbackDataDir = join(process.env.HOME ?? "/tmp", DEFAULT_DATA_DIR);
	return join(fallbackDataDir, DEFAULT_SOCKET_NAME);
}

/**
 * Thin HTTP-over-Unix-socket client for tapd. Mirrors the methods on the CLI's
 * `TapdClient` but uses Node's `http.request` with a `socketPath`, so the
 * OpenClaw plugin can talk to tapd from inside the Gateway process. Loads the
 * bearer token from `<dataDir>/.tapd-token` on each request — filesystem
 * permissions (0o600 on the token, 0o700 on the parent dir) are the first
 * line of defense, and the bearer token blocks a same-uid process that can
 * reach the socket but not read the token file.
 */
export class OpenClawTapdClient {
	private readonly socketPath: string;
	private readonly tokenPath: string;
	private readonly timeoutMs: number;

	constructor(options: OpenClawTapdClientOptions = {}) {
		this.socketPath = resolveSocketPath(options);
		this.tokenPath = join(dirname(this.socketPath), TOKEN_FILE_NAME);
		this.timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
	}

	get socketPathPublic(): string {
		return this.socketPath;
	}

	async health(): Promise<unknown> {
		return await this.get("/daemon/health");
	}

	async drainNotifications(): Promise<{ notifications: TapNotification[] }> {
		return await this.get<{ notifications: TapNotification[] }>("/api/notifications/drain");
	}

	async sendMessage(input: {
		peer: string;
		text: string;
		scope?: string;
		autoGenerated?: boolean;
		priority?: boolean;
	}): Promise<unknown> {
		return await this.post("/api/messages", input);
	}

	async connect(input: { inviteUrl: string; waitMs?: number }): Promise<unknown> {
		return await this.post("/api/connect", input);
	}

	async transfer(input: {
		asset: string;
		amount: string;
		chain?: string;
		toAddress: string;
	}): Promise<unknown> {
		return await this.post("/api/transfers", input);
	}

	async requestFunds(input: unknown): Promise<unknown> {
		return await this.post("/api/funds-requests", input);
	}

	async publishGrants(input: unknown): Promise<unknown> {
		return await this.post("/api/grants/publish", input);
	}

	async requestGrants(input: unknown): Promise<unknown> {
		return await this.post("/api/grants/request", input);
	}

	/**
	 * Post a meeting request to tapd's /api/meetings endpoint. Sends the
	 * flat shape tapd accepts alongside the full `{ peer, proposal }`
	 * back-compat shape — tapd builds the full SchedulingProposal
	 * internally (generating the schedulingId, defaulting slots to a
	 * placeholder ~24h ahead or to the caller-supplied `preferred` time,
	 * defaulting originTimezone to the daemon's local zone). The OpenClaw
	 * plugin never builds proposals itself.
	 */
	async requestMeeting(input: {
		peer: string;
		title: string;
		duration: number;
		preferred?: string;
		location?: string;
		note?: string;
		schedulingId?: string;
	}): Promise<unknown> {
		return await this.post("/api/meetings", input);
	}

	async respondMeeting(schedulingId: string, input: unknown): Promise<unknown> {
		return await this.post(`/api/meetings/${encodeURIComponent(schedulingId)}/respond`, input);
	}

	async cancelMeeting(schedulingId: string, input: unknown): Promise<unknown> {
		return await this.post(`/api/meetings/${encodeURIComponent(schedulingId)}/cancel`, input);
	}

	async listPending(): Promise<unknown> {
		return await this.get("/api/pending");
	}

	async resolvePending(
		requestId: string,
		approve: boolean,
		body: { note?: string; reason?: string } = {},
	): Promise<unknown> {
		const verb = approve ? "approve" : "deny";
		return await this.post(`/api/pending/${encodeURIComponent(requestId)}/${verb}`, body);
	}

	async createInvite(input: { expiresInSeconds?: number } = {}): Promise<unknown> {
		return await this.post("/api/invites", input);
	}

	async sync(): Promise<unknown> {
		return await this.post("/daemon/sync", {});
	}

	async shutdown(): Promise<unknown> {
		return await this.post("/daemon/shutdown", {});
	}

	private get<T = unknown>(path: string): Promise<T> {
		return this.request<T>("GET", path, undefined);
	}

	private post<T = unknown>(path: string, body: unknown): Promise<T> {
		return this.request<T>("POST", path, body);
	}

	private async loadToken(): Promise<string> {
		try {
			const token = (await readFile(this.tokenPath, "utf-8")).trim();
			if (!token) throw new Error(`tapd token file ${this.tokenPath} is empty`);
			return token;
		} catch (err: unknown) {
			const code = (err as NodeJS.ErrnoException | undefined)?.code;
			if (code === "ENOENT") {
				throw new TapdNotRunningError(this.socketPath);
			}
			throw err;
		}
	}

	private async request<T>(method: string, path: string, body: unknown): Promise<T> {
		const token = await this.loadToken();
		return new Promise<T>((resolve, reject) => {
			const payload = body !== undefined ? JSON.stringify(body) : undefined;
			const headers: Record<string, string> = {
				Accept: "application/json",
				Authorization: `Bearer ${token}`,
			};
			if (payload !== undefined) {
				headers["Content-Type"] = "application/json";
				headers["Content-Length"] = String(Buffer.byteLength(payload));
			}

			const req = request(
				{
					socketPath: this.socketPath,
					method,
					path,
					headers,
					timeout: this.timeoutMs,
				},
				(res) => {
					const chunks: Buffer[] = [];
					res.on("data", (chunk: Buffer) => chunks.push(chunk));
					res.on("end", () => {
						const raw = Buffer.concat(chunks).toString("utf-8");
						let parsed: unknown;
						try {
							parsed = raw ? JSON.parse(raw) : undefined;
						} catch {
							reject(
								new TapdHttpError(
									res.statusCode ?? 0,
									"invalid_json",
									`tapd returned invalid JSON: ${raw.slice(0, 200)}`,
								),
							);
							return;
						}
						if ((res.statusCode ?? 0) >= 400) {
							const error = (parsed as { error?: { code?: string; message?: string } } | undefined)
								?.error;
							reject(
								new TapdHttpError(
									res.statusCode ?? 0,
									error?.code ?? "unknown",
									error?.message ?? `tapd returned HTTP ${res.statusCode}`,
								),
							);
							return;
						}
						resolve(parsed as T);
					});
					res.on("error", reject);
				},
			);

			req.on("error", (err: NodeJS.ErrnoException) => {
				if (err.code === "ENOENT" || err.code === "ECONNREFUSED") {
					reject(new TapdNotRunningError(this.socketPath));
				} else {
					reject(err);
				}
			});

			req.on("timeout", () => {
				req.destroy();
				reject(new Error(`tapd request timed out after ${this.timeoutMs}ms`));
			});

			if (payload !== undefined) {
				req.write(payload);
			}
			req.end();
		});
	}
}
