import { Type } from "@sinclair/typebox";
import type { AnyAgentTool } from "openclaw/plugin-sdk";
import { isEthereumAddress, normalizeGrantInput } from "trusted-agents-core";
import type { OpenClawTapdClient } from "./tapd-client.js";

const ACTIONS = [
	"status",
	"sync",
	"restart",
	"create_invite",
	"connect",
	"send_message",
	"publish_grants",
	"request_grants",
	"request_funds",
	"transfer",
	"request_meeting",
	"respond_meeting",
	"cancel_meeting",
	"list_pending",
	"resolve_pending",
] as const;

function stringEnum<T extends readonly string[]>(values: T, description: string) {
	return Type.Unsafe<T[number]>({
		type: "string",
		enum: [...values],
		description,
	});
}

export const TapGatewayToolSchema = Type.Object(
	{
		action: stringEnum(ACTIONS, `Action to perform: ${ACTIONS.join(", ")}`),
		identity: Type.Optional(
			Type.String({
				description:
					"Configured TAP identity name. Required when more than one identity is configured.",
			}),
		),
		peer: Type.Optional(Type.String({ description: "Peer name or agent ID" })),
		inviteUrl: Type.Optional(Type.String({ description: "Trusted Agents invite URL" })),
		text: Type.Optional(Type.String({ description: "Message text" })),
		scope: Type.Optional(Type.String({ description: "TAP message scope" })),
		autoGenerated: Type.Optional(
			Type.Boolean({ description: "Set true for auto-generated replies to prevent reply loops" }),
		),
		priority: Type.Optional(
			Type.Boolean({
				description:
					"Pay the peer's priority attention price so the message escalates and may wake their agent",
			}),
		),
		note: Type.Optional(Type.String({ description: "Optional operator note" })),
		grantSet: Type.Optional(
			Type.Unknown({
				description: "Grant array or tap-grants/v1 object",
			}),
		),
		requestId: Type.Optional(Type.String({ description: "Pending TAP request ID" })),
		approve: Type.Optional(Type.Boolean({ description: "Approve or reject the pending request" })),
		asset: Type.Optional(
			Type.Union([Type.Literal("native"), Type.Literal("usdc")], {
				description: "Requested transfer asset",
			}),
		),
		amount: Type.Optional(Type.String({ description: "Transfer amount as a string" })),
		chain: Type.Optional(Type.String({ description: "CAIP-2 chain ID override" })),
		toAddress: Type.Optional(Type.String({ description: "Recipient address for fund requests" })),
		expiresInSeconds: Type.Optional(
			Type.Number({ description: "Invite expiry in seconds", minimum: 1 }),
		),
		title: Type.Optional(Type.String({ description: "Meeting title" })),
		duration: Type.Optional(
			Type.Number({ description: "Meeting duration in minutes", minimum: 1 }),
		),
		preferred: Type.Optional(
			Type.String({ description: "Preferred meeting time in ISO 8601 format" }),
		),
		location: Type.Optional(Type.String({ description: "Optional meeting location" })),
		schedulingId: Type.Optional(Type.String({ description: "Scheduling request ID" })),
		meetingAction: Type.Optional(
			Type.Union([Type.Literal("accept"), Type.Literal("reject")], {
				description: "Response action for a meeting request (accept or reject)",
			}),
		),
		reason: Type.Optional(
			Type.String({ description: "Optional reason for rejection or cancellation" }),
		),
	},
	{ additionalProperties: false },
);

interface TapGatewayToolParams {
	action: (typeof ACTIONS)[number];
	identity?: string;
	peer?: string;
	inviteUrl?: string;
	text?: string;
	scope?: string;
	autoGenerated?: boolean;
	priority?: boolean;
	note?: string;
	grantSet?: unknown;
	requestId?: string;
	approve?: boolean;
	asset?: "native" | "usdc";
	amount?: string;
	chain?: string;
	toAddress?: string;
	expiresInSeconds?: number;
	title?: string;
	duration?: number;
	preferred?: string;
	location?: string;
	schedulingId?: string;
	meetingAction?: "accept" | "reject";
	reason?: string;
}

export function createTapGatewayTool(client: OpenClawTapdClient): AnyAgentTool {
	return {
		name: "tap_gateway",
		label: "TAP Gateway",
		description:
			"Operate the Trusted Agents Protocol via the local tapd daemon. Use this for status, sync, connect, messaging, grants, fund requests, transfers, and pending approval resolution.",
		parameters: TapGatewayToolSchema,
		async execute(_toolCallId, params) {
			return json(await executeTapGatewayAction(client, params as TapGatewayToolParams));
		},
	} as AnyAgentTool;
}

async function executeTapGatewayAction(
	client: OpenClawTapdClient,
	params: TapGatewayToolParams,
): Promise<unknown> {
	switch (params.action) {
		case "status":
			return await client.health();
		case "sync":
			return await client.sync();
		case "restart":
			// tapd is a separate process; the plugin is a thin HTTP client
			// over its unix socket (CLAUDE.md §16, thin-plugin rule). The
			// plugin has no spawn capability, so calling `client.shutdown()`
			// alone leaves tapd down — an apparent recovery action becomes a
			// silent outage. Fail loudly and direct the operator to the CLI
			// surface that actually performs a stop+start cycle.
			throw new Error(
				"tap_gateway cannot restart tapd from within the plugin. Run `tap daemon restart` (or `tap hermes restart`) from the CLI, or restart the OpenClaw Gateway process to re-run the Hermes startup hook.",
			);
		case "create_invite":
			return await client.createInvite({ expiresInSeconds: params.expiresInSeconds });
		case "connect":
			return await client.connect({
				inviteUrl: requireString(params.inviteUrl, "inviteUrl"),
			});
		case "send_message":
			return await client.sendMessage({
				peer: requireString(params.peer, "peer"),
				text: requireString(params.text, "text"),
				scope: optionalString(params.scope),
				autoGenerated: params.autoGenerated,
				priority: params.priority,
			});
		case "publish_grants":
			return await client.publishGrants({
				peer: requireString(params.peer, "peer"),
				grantSet: normalizeGrantInput(params.grantSet),
				note: optionalString(params.note),
			});
		case "request_grants":
			return await client.requestGrants({
				peer: requireString(params.peer, "peer"),
				grantSet: normalizeGrantInput(params.grantSet),
				note: optionalString(params.note),
			});
		case "request_funds":
			return await client.requestFunds({
				peer: requireString(params.peer, "peer"),
				asset: params.asset ?? "native",
				amount: requireAmount(params.amount, "amount"),
				chain: optionalString(params.chain),
				toAddress: normalizeAddress(params.toAddress),
				note: optionalString(params.note),
			});
		case "transfer":
			return await client.transfer({
				asset: params.asset ?? "native",
				amount: requireAmount(params.amount, "amount"),
				chain: optionalString(params.chain),
				toAddress: requireAddress(params.toAddress, "toAddress"),
			});
		case "request_meeting":
			return await client.requestMeeting({
				peer: requireString(params.peer, "peer"),
				title: requireString(params.title, "title"),
				duration: typeof params.duration === "number" ? params.duration : 60,
				preferred: optionalString(params.preferred),
				location: optionalString(params.location),
				note: optionalString(params.note),
			});
		case "respond_meeting":
			return await client.respondMeeting(requireString(params.schedulingId, "schedulingId"), {
				approve: requireMeetingAccept(params.meetingAction),
				reason: optionalString(params.reason),
			});
		case "cancel_meeting":
			return await client.cancelMeeting(requireString(params.schedulingId, "schedulingId"), {
				reason: optionalString(params.reason),
			});
		case "list_pending":
			return await client.listPending();
		case "resolve_pending":
			return await client.resolvePending(
				requireString(params.requestId, "requestId"),
				requireBoolean(params.approve, "approve"),
				{ note: optionalString(params.note), reason: optionalString(params.reason) },
			);
		default:
			params.action satisfies never;
			throw new Error(`Unsupported TAP Gateway action: ${String(params.action)}`);
	}
}

function json(payload: unknown): {
	content: Array<{ type: "text"; text: string }>;
	details: unknown;
} {
	return {
		content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
		details: payload,
	};
}

function requireString(value: string | undefined, name: string): string {
	if (typeof value !== "string" || value.trim().length === 0) {
		throw new Error(`${name} is required`);
	}
	return value.trim();
}

function requireAmount(value: string | undefined, name: string): string {
	const trimmed = requireString(value, name);
	const parsed = Number(trimmed);
	if (!Number.isFinite(parsed) || parsed <= 0) {
		throw new Error(
			`${name} must be a positive number (got: ${trimmed}). Use a decimal string like "0.5".`,
		);
	}
	return trimmed;
}

function optionalString(value: string | undefined): string | undefined {
	return typeof value === "string" && value.trim().length > 0 ? value.trim() : undefined;
}

function requireBoolean(value: boolean | undefined, name: string): boolean {
	if (typeof value !== "boolean") {
		throw new Error(`${name} is required`);
	}
	return value;
}

function requireAddress(value: string | undefined, name: string): `0x${string}` {
	const addr = validateAddress(value);
	if (!addr) throw new Error(`${name} is required`);
	return addr;
}

function normalizeAddress(value: string | undefined): `0x${string}` | undefined {
	return validateAddress(value) ?? undefined;
}

function validateAddress(value: string | undefined): `0x${string}` | null {
	if (value === undefined || value.trim().length === 0) return null;
	if (!isEthereumAddress(value)) throw new Error(`Invalid Ethereum address: ${value}`);
	return value;
}

function requireMeetingAccept(value: "accept" | "reject" | undefined): boolean {
	if (value === "accept") return true;
	if (value === "reject") return false;
	throw new Error("meetingAction is required");
}
